### ISSUE TITLE
[1.12.2] Crash on Game Start - Null Pointer Exception

### ISSUE THREAD

**Issue by MasterEnderman** [darkevilmac/MovingWorld#51] opened 2018-02-19 18:21 UTC
Crah Report: https://pastebin.com/3EwGcn9y
Forge: 14.23.2.2618
MovingWorld: 6.342
Davincis Vessels: 6.340

**Comment by CcytherR** [comment] 2018-03-28 17:29
Same crash i think https://pastebin.com/E9FinxNe

**Comment by brisingraerowing** [comment] 2018-04-06 01:04
I get the same crash as well.

**Comment by SonnyLonglegs** [comment] 2018-04-07 22:58
I get the same crash.

**Comment by SonnyLonglegs** [comment] 2018-04-07 22:59
Apparently, according to the next issue down, it's caused by Redstone++.

**Comment by exaskye** [comment] 2018-04-07 23:00
Appears to be the same exception, yes.

Closing as a duplicate of #50

**Closed as completed by exaskye** 2018-04-07 23:00 UTC
Labels: duplicate
