### ISSUE TITLE
phantom duplicate mod issue

### ISSUE THREAD

**Issue by kreezxil** [darkevilmac/MovingWorld#11] opened 2015-07-23 18:02 UTC
Issue: moving world 1.8-alpha-3.2 on a dedicated server thinks there are duplicates when there are no duplicates

crash report:
https://gist.github.com/73873a7af82362f2940e

fml server latest:
https://gist.github.com/47df4043d959886790c9

**Comment by darkevilmac** [comment] 2015-07-23 22:00
Forge Version?
Does it occur with only MovingWorld installed on a fresh minecraft install?

**Comment by kreezxil** [comment] 2015-07-23 23:31
Forge b1493, it happens only with the latest mod version 3.2. 3.1-HFX
doesn't have this problem.

**Comment by darkevilmac** [comment] 2015-07-23 23:52
Can you try with only forge and movingworld installed, no other mods. I'm unable to recreate this crash.

**Comment by kreezxil** [comment] 2015-07-24 01:05
I think it all started when i installed Forge Essentials 1.8 which also uses a MIXINS subsystem. 

Tried as you suggested with no issues.

**Comment by darkevilmac** [comment] 2015-08-21 00:03
This is an issue with Mixins, as I've discovered. Unfortunately this is out of my control, when mixins fixes the issue it will work fine.

**Comment by Shtwophell** [comment] 2015-09-16 11:32
Has there been any update on this situation since july?

I am having the same duplicate mod error.

I dont want to get rid of moving worlds or forge essentials either as they are extremely usefull.

**Comment by darkevilmac** [comment] 2015-09-16 11:37
This is a bug that is caused by Mixins as you can see in my last post on this thread, please make sure you have the latest version of MovingWorld from CurseForge. If that build does not solve the issue for you I'm afraid there's nothing I can do as it's an issue from Mixins which the 1.8 iteration of MovingWorld heavily relies on.

**Comment by Shtwophell** [comment] 2015-09-16 12:35
Thank you for such a speedy response

I am sad to say that I have infact updated to the latest version.

I suppose this means there is nothing I will be able to do to fix this issue?

If not, Is mixins still in live development? and will it be updated in future, am I likely to be stuck with this issue forever?.

I would hate to go without movingworld as it is one of my favourite minecraft mods, however I have no idea how to set permissions on forge except with forgeessentials, perhaps there is an alternative?

**Comment by darkevilmac** [comment] 2015-09-16 23:49
Hmm, what version of MovingWorld are you using specifically, and what ForgeEssentials build are you using?

**Comment by Shtwophell** [comment] 2015-09-17 07:55
It was MovingWorld-MC1.8-V1.8.1 and forgeessentials-1.8-1.8.3.40-server   if that helps

**Comment by darkevilmac** [comment] 2015-09-19 06:45
Could you give me a full list of installed mods because there's a few others that use Mixins that could be causing the conflict.

**Comment by kreezxil** [comment] 2015-09-19 10:40
I know you are talking to the other guy, but since I opened this originally I'd like to point out that for me when I try to use the new Forge Essentials for 1.8 with Moving World I get this issue. I just confirmed it again recently as both you and the FE team released updates. Since I want what your mod provides more than what FE provides the choice is simple.

Also FE is the only other 1.8 mod that I am aware of that is using Mixins.

-----Original Message-----

**Comment by Shtwophell** [comment] 2015-09-19 11:48
Full list as requested:
Evs-Ivs-1.8-4.0.2-universal.jar
Fantastic-Foods-Mod-1.8.jar
PermissionForge-1.8.jar
Pixelmon-1.8-4.0.7-universal.jar
archimedesshipsplus-MC1.8-V1.8.jar
movingworld-MC1.8-V1.8.1.jar
pixelmonfriends-1.8-1.1.0-universal.jar

**Comment by kreezxil** [comment] 2015-09-19 12:36
Shtopwell I have an idea for you. Setup a test server. Take out Permission Forge and see if that stops the issue.


-----Original Message-----

**Comment by Shtwophell** [comment] 2015-09-19 12:56
Thank you Kreezxil, I just tried that, and it does stop the issue.

However I need an ability set permissions on my server and permission forge seems to be the only option?

I cant get rid of moving world either because all the player on my server love being able to use an airship,

**Comment by kreezxil** [comment] 2015-09-19 13:54
Sadly they're is no way to add permissions and use moving world. My permission manager of choice is Forge Essentials from forgeessentials.com as out does way more than Permissions Forge stick as supporting towns. However, because it uses Mixins Forge causes the duplicate mod issue. This really seems like a case where these author's need to report it to Lex Manos of Forge and also the Mixins team at Spongepowered simply because we mod pack developers have no control over this behavior other tab to only use one mod from the Mixins category.

The other option is for BenjaminK to record Moving World to not rely on Mixins. But I suspect that will a daunting task at this point in time and as far as he can tell only two mod pack developed, you and I, are having issues. This will of course change as more mod pack developers begin coming to 1.8 and report the issue more and more. Hopefully the Mixins team will fix the issue and save BenjaminK a major recoding bender.

-----Original Message-----

**Comment by Shtwophell** [comment] 2015-09-19 16:59
I hope you are right Kreezxil, its a real pain that none of my players have permission to use any of the other mods besides movingworld. But it is how it is.

I apreciate your advice.

**Comment by darkevilmac** [comment] 2015-09-19 17:16
I just checked on the Sponge IRC and it seems I was mistaken that the latest build of Mixins fixed the issue. It was a different fix for something else, opening the issue back up until there's a build of Mixins that fixes the problem.

Sorry for that, my mistake.

**Comment by Shtwophell** [comment] 2015-09-19 17:39
No need to apologise at all.

How could I go about finding out when the mixins is released and implemented in movingworld, would It be mentioned here at all?

**Comment by kreezxil** [comment] 2015-09-19 17:41
If you remove the permission system they'll have everything they need.

-----Original Message-----

**Comment by Shtwophell** [comment] 2015-09-19 17:44
I wish that was the case Kreezxil

But without a  permissions mod, they get the error "you do not have permission to use this command"

When trying to use the commands that come with some of the mods.

**Comment by kreezxil** [comment] 2015-09-19 19:29
I think I found your a solution. This permission mod has been around since
November 26, 2014 and doesn't appear to use Mixins at all (I read its
source).

http://minecraft.curseforge.com/mc-mods/224460-enhanced-server-moderation

Will likely solve your issue, it won't solve mine because I want all of the
power associated with FE but thankfully I don't have mods installed like
Pixelmon that depend on perms.

**Comment by Shtwophell** [comment] 2015-09-19 21:09
The permission mod I was using for this ticket was FE. Since having the posted issue I switched to permission forge, but it doesnt work either, its in alpha and hasnt been updated in a long time. I will need to use Forge essentials, but of course as it is dependent on mixins It is having the above issues.

**Comment by luacs1998** [comment] 2015-09-21 15:03
If it's a mixin issue... @Mumfrey? Any ideas?

**Comment by Mumfrey** [comment] 2015-09-21 15:09
There were noises about issue with duplicate injections of mod containers under 1.7.10 (obviously I can't verify as I have no 1.7.10 testbed) but I understood it to be an unrelated issue. Basically the issue lies with the mixin agent detecting whether or not it needs to inject a particular container (container injection is inhibited if the container is a tweaker, thus it needs to inject under those circumstances) and that watershed is detected [this way](https://github.com/SpongePowered/Mixin/blob/master/src/main/java/org/spongepowered/asm/launch/MixinLaunchAgentFML.java#L197-L204), which may not work under 1.7.10 for some reason.

If someone with a 1.7.10 workspace can verify the behaviour of this it would be useful, and maybe suggest an alternate detection method.

This is with 0.4.5 and later, before that it's basically not feasible that multiple mods can use mixin anyway, so ensure everything in question is using 0.4.5 or later.

**Comment by luacs1998** [comment] 2015-09-21 15:19
As far as I know FE is the only mod using mixins in 1.7.10 - this issue occurs in 1.8.

**Comment by Mumfrey** [comment] 2015-09-21 15:22
The logs in the issue mention 0.4.4, so is it possible that the error has since been resolved since it [looks like MovingWorld has updated](https://github.com/darkevilmac/MovingWorld/blob/master/build.gradle#L71) to 0.4.5?

**Comment by luacs1998** [comment] 2015-09-21 15:25
Nope, not resolved - according to [a log I received on IRC](http://pastebin.com/M0wQEC4x).

Apparently it's conflicting between the minecraft.jar and the minecraft.jar? I could attempt to hook up a debugger, but not sure how useful that would be.

**Comment by Mumfrey** [comment] 2015-09-21 15:28
Can you attempt to obtain the *fml-server-latest.log* for that scenario above?

**Comment by Shtwophell** [comment] 2015-09-21 15:30
http://pastebin.com/V5tN4jNu

fml-server-latest.log

**Comment by Mumfrey** [comment] 2015-09-21 15:38
I think I see the problem based on that last log. Because you are [creating a new instance of the mixin tweaker](https://github.com/ForgeEssentials/ForgeEssentials/blob/develop/src/main/java/com/forgeessentials/core/preloader/FELaunchHandler.java#L75) it's creating launch agents twice, because the entire point of the launch agent system is that a specific tweaker can only be loaded once. This previously meant that if multiple mods bundled mixin, only the first would actually load.

The launch agent system in 0.4.5 is designed such that the first mixin tweaker to load takes responsibility for scanning all other containers discovered by fml and co-operatively processing them as if the tweaker had loaded from those containers in the first place. I think what's happening is that because you're creating a second instance of the mixin tweaker (which is unexpected), it's doing that process *twice*.

I'm not 100% sure, and don't have time to investigate right now, but that's what it looks like.

**Comment by Mumfrey** [comment] 2015-09-21 15:43
If you want to do what you're doing, really the best way is to just honour the tweaker contract. Tweakers are supposed to load other tweakers by putting them on the blackboard so that they get loaded by `Launch` directly, *not* by instancing them themselves. I think if you do this then it should work as expected, because it will allow `Launch` to preserve the tweaker single-instance contract as intended.

**Comment by luacs1998** [comment] 2015-09-21 15:44
So it's a "bug" on my part that should be fixed? Thanks for the pointers.

**Comment by Mumfrey** [comment] 2015-09-21 15:53
Just an unintended confluence of circumstances, nobody's fault since we both just assumed we understood the landscape and clearly there are other factors. If you try what I've suggested and see how it goes from there, hopefully it'll be good. You just need to put your mixin config declarations in the jar manifest instead of adding them declaritively.

**Comment by luacs1998** [comment] 2015-09-21 15:57
One more question: To put a tweaker on the blackboard, how would I do it? Adding a String "org.spongepowered.asm.launch.MixinTweaker" to the TweakClasses entry on the Launch.blackboard gives me a ConcurrentModificationException.

**Comment by Mumfrey** [comment] 2015-09-21 16:03
You can only add tweakers from inside one of the `ITweaker` callback methods, you can't do it from within a tweaker constructor.

**Comment by luacs1998** [comment] 2015-09-21 16:23
It works now. @Shtwophell update to FE build 43.

@darkevilmac you can close this, sorry for the trouble

**Comment by Mumfrey** [comment] 2015-09-21 16:31
Do I get a cookie?

**Comment by Shtwophell** [comment] 2015-09-21 18:38
This worked perfectly! thank you both

**Comment by darkevilmac** [comment] 2015-09-22 01:30
I go to sleep, wake up, and people solved an issue.

I should sleep more often.

**Closed by darkevilmac** 2015-09-22 01:30 UTC
